import { ObjectSelectOptionModel } from "../Types/Models";

const icons: ObjectSelectOptionModel[] = [
    { icon: 'pi-address-book', label: 'Address Book' },
    { icon: 'pi-align-center', label: 'Align Center' },
    { icon: 'pi-align-justify', label: 'Align Justify' },
    { icon: 'pi-align-left', label: 'Align Left' },
    { icon: 'pi-align-right', label: 'Align Right' },
    { icon: 'pi-amazon', label: 'Amazon' },
    { icon: 'pi-android', label: 'Android' },
    { icon: 'pi-angle-double-down', label: 'Angle Double Down' },
    { icon: 'pi-angle-double-left', label: 'Angle Double Left' },
    { icon: 'pi-angle-double-right', label: 'Angle Double Right' },
    { icon: 'pi-angle-double-up', label: 'Angle Double Up' },
    { icon: 'pi-angle-down', label: 'Angle Down' },
    { icon: 'pi-angle-left', label: 'Angle Left' },
    { icon: 'pi-angle-right', label: 'Angle Right' },
    { icon: 'pi-angle-up', label: 'Angle Up' },
    { icon: 'pi-apple', label: 'Apple' },
    { icon: 'pi-arrow-circle-down', label: 'Arrow Circle Down' },
    { icon: 'pi-arrow-circle-left', label: 'Arrow Circle Left' },
    { icon: 'pi-arrow-circle-right', label: 'Arrow Circle Right' },
    { icon: 'pi-arrow-circle-up', label: 'Arrow Circle Up' },
    { icon: 'pi-arrow-down', label: 'Arrow Down' },
    { icon: 'pi-arrow-down-left', label: 'Arrow Down Left' },
    { icon: 'pi-arrow-down-left-and-arrow-up-right-to-center', label: 'Arrow Together' },
    { icon: 'pi-arrow-down-right', label: 'Arrow Down Right' },
    { icon: 'pi-arrow-left', label: 'Arrow Left' },
    { icon: 'pi-arrow-right', label: 'Arrow Right' },
    { icon: 'pi-arrow-right-arrow-left', label: 'Arrow Right Arrow Left' },
    { icon: 'pi-arrow-up', label: 'Arrow Up' },
    { icon: 'pi-arrow-up-left', label: 'Arrow Up Left' },
    { icon: 'pi-arrow-up-right', label: 'Arrow Up Right' },
    { icon: 'pi-arrow-up-right-and-arrow-down-left-from-center', label: 'Arrow Away' },
    { icon: 'pi-arrows-alt', label: 'Arrows Alt' },
    { icon: 'pi-arrows-h', label: 'Arrows Horizontal' },
    { icon: 'pi-arrows-v', label: 'Arrows Vertical' },
    { icon: 'pi-asterisk', label: 'Asterisk' },
    { icon: 'pi-at', label: 'At' },
    { icon: 'pi-backward', label: 'Backward' },
    { icon: 'pi-ban', label: 'Ban' },
    { icon: 'pi-barcode', label: 'Barcode' },
    { icon: 'pi-bars', label: 'Bars' },
    { icon: 'pi-bell', label: 'Bell' },
    { icon: 'pi-bell-slash', label: 'Bell Slash' },
    { icon: 'pi-bitcoin', label: 'Bitcoin' },
    { icon: 'pi-bolt', label: 'Bolt' },
    { icon: 'pi-book', label: 'Book' },
    { icon: 'pi-bookmark', label: 'Bookmark' },
    { icon: 'pi-bookmark-fill', label: 'Bookmark Fill' },
    { icon: 'pi-box', label: 'Box' },
    { icon: 'pi-briefcase', label: 'Briefcase' },
    { icon: 'pi-building', label: 'Building' },
    { icon: 'pi-building-columns', label: 'Building Columns' },
    { icon: 'pi-bullseye', label: 'Bullseye' },
    { icon: 'pi-calculator', label: 'Calculator' },
    { icon: 'pi-calendar', label: 'Calendar' },
    { icon: 'pi-calendar-clock', label: 'Clock' },
    { icon: 'pi-calendar-minus', label: 'Minus' },
    { icon: 'pi-calendar-plus', label: 'Plus' },
    { icon: 'pi-calendar-times', label: 'Times' },
    { icon: 'pi-camera', label: 'Camera' },
    { icon: 'pi-car', label: 'Car' },
    { icon: 'pi-caret-down', label: 'Caret Down' },
    { icon: 'pi-caret-left', label: 'Caret Left' },
    { icon: 'pi-caret-right', label: 'Caret Right' },
    { icon: 'pi-caret-up', label: 'Caret Up' },
    { icon: 'pi-cart-arrow-down', label: 'Cart Arrow Down' },
    { icon: 'pi-cart-minus', label: 'Cart Minus' },
    { icon: 'pi-cart-plus', label: 'Cart Plus' },
    { icon: 'pi-chart-bar', label: 'Chart Bar' },
    { icon: 'pi-chart-line', label: 'Chart Line' },
    { icon: 'pi-chart-pie', label: 'Chart Pie' },
    { icon: 'pi-chart-scatter', label: 'Chart Scatter' },
    { icon: 'pi-check', label: 'Check' },
    { icon: 'pi-check-circle', label: 'Check Circle' },
    { icon: 'pi-check-square', label: 'Check Square' },
    { icon: 'pi-chevron-circle-down', label: 'Chevron Circle Down' },
    { icon: 'pi-chevron-circle-left', label: 'Chevron Circle Left' },
    { icon: 'pi-chevron-circle-right', label: 'Chevron Circle Right' },
    { icon: 'pi-chevron-circle-up', label: 'Chevron Circle Up' },
    { icon: 'pi-chevron-down', label: 'Chevron Down' },
    { icon: 'pi-chevron-left', label: 'Chevron Left' },
    { icon: 'pi-chevron-right', label: 'Chevron Right' },
    { icon: 'pi-chevron-up', label: 'Chevron up' },
    { icon: 'pi-circle', label: 'Circle' },
    { icon: 'pi-circle-fill', label: 'Circle Fill' },
    { icon: 'pi-clipboard', label: 'Clipboard' },
    { icon: 'pi-clock', label: 'Clock' },
    { icon: 'pi-clone', label: 'Clone' },
    { icon: 'pi-cloud', label: 'Cloud' },
    { icon: 'pi-cloud-download', label: 'Cloud Download' },
    { icon: 'pi-cloud-upload', label: 'Cloud Upload' },
    { icon: 'pi-code', label: 'Code' },
    { icon: 'pi-cog', label: 'Cog' },
    { icon: 'pi-comment', label: 'Comment' },
    { icon: 'pi-comments', label: 'Comments' },
    { icon: 'pi-compass', label: 'Compass' },
    { icon: 'pi-copy', label: 'Copy' },
    { icon: 'pi-credit-card', label: 'Credit Card' },
    { icon: 'pi-crown', label: 'Crown' },
    { icon: 'pi-database', label: 'Database' },
    { icon: 'pi-delete-left', label: 'Delete Left' },
    { icon: 'pi-desktop', label: 'Desktop' },
    { icon: 'pi-directions', label: 'Directions' },
    { icon: 'pi-directions-alt', label: 'Directions Alt' },
    { icon: 'pi-discord', label: 'Discord' },
    { icon: 'pi-dollar', label: 'Dollar' },
    { icon: 'pi-download', label: 'Download' },
    { icon: 'pi-eject', label: 'Eject' },
    { icon: 'pi-ellipsis-h', label: 'Ellipsis Horizontal' },
    { icon: 'pi-ellipsis-v', label: 'Ellipsis Vertical' },
    { icon: 'pi-envelope', label: 'Envelope' },
    { icon: 'pi-equals', label: 'Equals' },
    { icon: 'pi-eraser', label: 'Eraser' },
    { icon: 'pi-ethereum', label: 'Ethereum' },
    { icon: 'pi-euro', label: 'Euro' },
    { icon: 'pi-exclamation-circle', label: 'Exclamation Circle' },
    { icon: 'pi-exclamation-triangle', label: 'Exclamation Triangle' },
    { icon: 'pi-expand', label: 'Expand' },
    { icon: 'pi-external-link', label: 'External Link' },
    { icon: 'pi-eye', label: 'Eye' },
    { icon: 'pi-eye-slash', label: 'Eye Slash' },
    { icon: 'pi-face-smile', label: 'Face Smaile' },
    { icon: 'pi-facebook', label: 'Facebook' },
    { icon: 'pi-fast-backward', label: 'Fast Backward' },
    { icon: 'pi-fast-forward', label: 'Fast Forward' },
    { icon: 'pi-file', label: 'File' },
    { icon: 'pi-file-arrow-up', label: 'File Arrow Up' },
    { icon: 'pi-file-check', label: 'File Check' },
    { icon: 'pi-file-edit', label: 'File Edit' },
    { icon: 'pi-file-excel', label: 'File Excel' },
    { icon: 'pi-file-export', label: 'File Export' },
    { icon: 'pi-file-import', label: 'File Import' },
    { icon: 'pi-file-pdf', label: 'File PDF' },
    { icon: 'pi-file-plus', label: 'File Plus' },
    { icon: 'pi-file-word', label: 'File Word' },
    { icon: 'pi-filter', label: 'Filter' },
    { icon: 'pi-filter-fill', label: 'Filter Fill' },
    { icon: 'pi-filter-slash', label: 'Filter Slash' },
    { icon: 'pi-flag', label: 'Flag' },
    { icon: 'pi-flag-fill', label: 'Flag Fill' },
    { icon: 'pi-folder', label: 'Folder' },
    { icon: 'pi-folder-open', label: 'Folder Open' },
    { icon: 'pi-folder-plus', label: 'Folder Plus' },
    { icon: 'pi-forward', label: 'Forward' },
    { icon: 'pi-gauge', label: 'Gauge' },
    { icon: 'pi-gift', label: 'Gift' },
    { icon: 'pi-github', label: 'Github' },
    { icon: 'pi-globe', label: 'Globe' },
    { icon: 'pi-google', label: 'Google' },
    { icon: 'pi-graduation-cap', label: 'Graduation Cap' },
    { icon: 'pi-hammer', label: 'Hammer' },
    { icon: 'pi-hashtag', label: 'Hashtag' },
    { icon: 'pi-headphones', label: 'Headphones' },
    { icon: 'pi-heart', label: 'Heart' },
    { icon: 'pi-heart-fill', label: 'Heart Fill' },
    { icon: 'pi-history', label: 'History' },
    { icon: 'pi-home', label: 'Home' },
    { icon: 'pi-hourglass', label: 'Hourglass' },
    { icon: 'pi-id-card', label: 'ID Card' },
    { icon: 'pi-image', label: 'Image' },
    { icon: 'pi-images', label: 'Images' },
    { icon: 'pi-inbox', label: 'Inbox' },
    { icon: 'pi-indian-rupee', label: 'Indian Rupee' },
    { icon: 'pi-info', label: 'Info' },
    { icon: 'pi-info-circle', label: 'Info Circle' },
    { icon: 'pi-instagram', label: 'Instagram' },
    { icon: 'pi-key', label: 'Key' },
    { icon: 'pi-language', label: 'Language' },
    { icon: 'pi-lightbulb', label: 'Lightbulb' },
    { icon: 'pi-link', label: 'Link' },
    { icon: 'pi-linkedin', label: 'Linkedin' },
    { icon: 'pi-list', label: 'List' },
    { icon: 'pi-list-check', label: 'List Check' },
    { icon: 'pi-lock', label: 'Lock' },
    { icon: 'pi-lock-open', label: 'Lock Open' },
    { icon: 'pi-map', label: 'Map' },
    { icon: 'pi-map-marker', label: 'Map Marker' },
    { icon: 'pi-mars', label: 'Mars' },
    { icon: 'pi-megaphone', label: 'Megaphone' },
    { icon: 'pi-microchip', label: 'Microchip' },
    { icon: 'pi-microchip-ai', label: 'Microchip AI' },
    { icon: 'pi-microphone', label: 'Microphone' },
    { icon: 'pi-microsoft', label: 'Microsoft' },
    { icon: 'pi-minus', label: 'Minus' },
    { icon: 'pi-minus-circle', label: 'Minus Circle' },
    { icon: 'pi-mobile', label: 'Mobile' },
    { icon: 'pi-money-bill', label: 'Money Bill' },
    { icon: 'pi-moon', label: 'Moon' },
    { icon: 'pi-objects-column', label: 'Objects Column' },
    { icon: 'pi-palette', label: 'Palette' },
    { icon: 'pi-paperclip', label: 'Paperclip' },
    { icon: 'pi-pause', label: 'Pause' },
    { icon: 'pi-pause-circle', label: 'Pause Circle' },
    { icon: 'pi-paypal', label: 'Paypal' },
    { icon: 'pi-pen-to-square', label: 'Pen To Square' },
    { icon: 'pi-pencil', label: 'Pencil' },
    { icon: 'pi-percentage', label: 'Percentage' },
    { icon: 'pi-phone', label: 'Phone' },
    { icon: 'pi-pinterest', label: 'Pinterest' },
    { icon: 'pi-play', label: 'Play' },
    { icon: 'pi-play-circle', label: 'Play Circle' },
    { icon: 'pi-plus', label: 'Plus' },
    { icon: 'pi-plus-circle', label: 'Plus Circle' },
    { icon: 'pi-pound', label: 'Pound' },
    { icon: 'pi-power-off', label: 'Power Off' },
    { icon: 'pi-prime', label: 'Prime' },
    { icon: 'pi-print', label: 'Print' },
    { icon: 'pi-qrcode', label: 'QR Code' },
    { icon: 'pi-question', label: 'Question' },
    { icon: 'pi-question-circle', label: 'Question Circle' },
    { icon: 'pi-receipt', label: 'Receipt' },
    { icon: 'pi-reddit', label: 'Reddit' },
    { icon: 'pi-refresh', label: 'Refresh' },
    { icon: 'pi-replay', label: 'Replay' },
    { icon: 'pi-reply', label: 'Reply' },
    { icon: 'pi-save', label: 'Save' },
    { icon: 'pi-search', label: 'Search' },
    { icon: 'pi-search-minus', label: 'search Minus' },
    { icon: 'pi-search-plus', label: 'Search Plus' },
    { icon: 'pi-send', label: 'Send' },
    { icon: 'pi-server', label: 'Server' },
    { icon: 'pi-share-alt', label: 'Share Alt' },
    { icon: 'pi-shield', label: 'Shield' },
    { icon: 'pi-shop', label: 'Shop' },
    { icon: 'pi-shopping-bag', label: 'Shopping Bag' },
    { icon: 'pi-shopping-cart', label: 'Shopping Cart' },
    { icon: 'pi-sign-in', label: 'Sign In' },
    { icon: 'pi-sign-out', label: 'Sign Out' },
    { icon: 'pi-sitemap', label: 'Sitemap' },
    { icon: 'pi-slack', label: 'Slack' },
    { icon: 'pi-sliders-h', label: 'Sliders Horizontal' },
    { icon: 'pi-sliders-v', label: 'Sliders Vertical' },
    { icon: 'pi-sort', label: 'Sort' },
    { icon: 'pi-sort-alpha-down', label: 'Sort Alpha Down' },
    { icon: 'pi-sort-alpha-down-alt', label: 'Sort Alpha Down Alt' },
    { icon: 'pi-sort-alpha-up', label: 'Sort Alpha Up' },
    { icon: 'pi-sort-alpha-up-alt', label: 'Sort Alpha Up Alt' },
    { icon: 'pi-sort-alt', label: 'Sort Alt' },
    { icon: 'pi-sort-alt-slash', label: 'Sort Alt Slash' },
    { icon: 'pi-sort-amount-down', label: 'Sort Amount Down' },
    { icon: 'pi-sort-amount-down-alt', label: 'Sort Amount Down Alt' },
    { icon: 'pi-sort-amount-up', label: 'Sort Amount Up' },
    { icon: 'pi-sort-amount-up-alt', label: 'Sort Amount Up Alt' },
    { icon: 'pi-sort-down', label: 'Sort Down' },
    { icon: 'pi-sort-down-fill', label: 'Sort Down Fill' },
    { icon: 'pi-sort-numeric-down', label: 'Sort Numeric Down' },
    { icon: 'pi-sort-numeric-down-alt', label: 'Sort Numeric Down Alt' },
    { icon: 'pi-sort-numeric-up', label: 'Sort Numeric Up' },
    { icon: 'pi-sort-numeric-up-alt', label: 'Sort Numeric Up Alt' },
    { icon: 'pi-sort-up', label: 'Sort Up' },
    { icon: 'pi-sort-up-fill', label: 'Sort Up Fill' },
    { icon: 'pi-sparkles', label: 'Sparkles' },
    { icon: 'pi-spinner', label: 'Spinner' },
    { icon: 'pi-spinner-dotted', label: 'Spinner Dotted' },
    { icon: 'pi-star', label: 'Start' },
    { icon: 'pi-star-fill', label: 'Start Fill' },
    { icon: 'pi-star-half', label: 'Star Half' },
    { icon: 'pi-star-half-fill', label: 'Star Half Fill' },
    { icon: 'pi-step-backward', label: 'Step Backward' },
    { icon: 'pi-step-backward-alt', label: 'Step Backward Alt' },
    { icon: 'pi-step-forward', label: 'Step Forward' },
    { icon: 'pi-step-forward-alt', label: 'Step Forward Alt' },
    { icon: 'pi-stop', label: 'Stop' },
    { icon: 'pi-stop-circle', label: 'Stop Circle' },
    { icon: 'pi-stopwatch', label: 'Stopwatch' },
    { icon: 'pi-sun', label: 'Sun' },
    { icon: 'pi-sync', label: 'Sync' },
    { icon: 'pi-table', label: 'Table' },
    { icon: 'pi-tablet', label: 'Tablet' },
    { icon: 'pi-tag', label: 'Tag' },
    { icon: 'pi-tags', label: 'Tags' },
    { icon: 'pi-telegram', label: 'Telegram' },
    { icon: 'pi-th-large', label: 'TH Large' },
    { icon: 'pi-thumbs-down', label: 'Thumbs Down' },
    { icon: 'pi-thumbs-down-fill', label: 'Thumbs Down Fill' },
    { icon: 'pi-thumbs-up', label: 'Thumbs Up' },
    { icon: 'pi-thumbs-up-fill', label: 'Thumbs Up Fill' },
    { icon: 'pi-thumbtack', label: 'Thumbtack' },
    { icon: 'pi-ticket', label: 'Ticket' },
    { icon: 'pi-tiktok', label: 'Tiktok' },
    { icon: 'pi-times', label: 'Times' },
    { icon: 'pi-times-circle', label: 'Times Circle' },
    { icon: 'pi-trash', label: 'Trash' },
    { icon: 'pi-trophy', label: 'Trophy' },
    { icon: 'pi-truck', label: 'Truck' },
    { icon: 'pi-turkish-lira', label: 'Turkish Lira' },
    { icon: 'pi-twitch', label: 'Twitch' },
    { icon: 'pi-twitter', label: 'Twitter' },
    { icon: 'pi-undo', label: 'Undo' },
    { icon: 'pi-unlock', label: 'Unlock' },
    { icon: 'pi-upload', label: 'Upload' },
    { icon: 'pi-user', label: 'User' },
    { icon: 'pi-user-edit', label: 'User Edit' },
    { icon: 'pi-user-minus', label: 'User Minus' },
    { icon: 'pi-user-plus', label: 'User Plus' },
    { icon: 'pi-users', label: 'Users' },
    { icon: 'pi-venus', label: 'Venus' },
    { icon: 'pi-verified', label: 'Verified' },
    { icon: 'pi-video', label: 'Video' },
    { icon: 'pi-vimeo', label: 'Vimeo' },
    { icon: 'pi-volume-down', label: 'Volume Down' },
    { icon: 'pi-volume-off', label: 'Volume Off' },
    { icon: 'pi-volume-up', label: 'Volume Up' },
    { icon: 'pi-wallet', label: 'Wallet' },
    { icon: 'pi-warehouse', label: 'Warehouse' },
    { icon: 'pi-wave-pulse', label: 'Wave Pluse' },
    { icon: 'pi-whatsapp', label: 'Whatsapp' },
    { icon: 'pi-wifi', label: 'WiFi' },
    { icon: 'pi-window-maximize', label: 'Window Maximize' },
    { icon: 'pi-window-minimize', label: 'Window Minimize' },
    { icon: 'pi-wrench', label: 'Wrench' },
    { icon: 'pi-youtube', label: 'Youtube' },
];
export default icons;